config/routes.rb
Rails.application.routes.draw do
  root 'inventory#index'

  get 'enter_book' => 'inventory#enter_book'
  post 'enter_book' => 'inventory#enter_book'

  get 'find_book' => 'inventory#find_book'
  post 'find_book' => 'inventory#find_book'

end

app/models/book.rb
class Book < ActiveRecord::Base

    belongs_to :shelf

end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
    
    has_many :books
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def index
  end

  def enter_book
    @shelves = Shelf.all
    @books = Book.all
    @author_entry = false
    
    if params[:title] != nil
      @book = Book.new
      @book.title = params[:title]
      @book.author = params[:author]
      @book.color = params[:color]
      @book.shelf_id = params[:shelf_id]
      @book.save
      if params[:author_entry] == "true"
        @author_entry = true
        @author_name = params[:author]
      end
    end
  end

  def find_book
    @showtime = false
    @search_type = ""
    if params[:title] != nil
      @book = Book.find_by(title: params[:title])
      @showtime = true
      @search_type = "by title"
    elsif params[:author] != nil
      @books = Book.where(author: params[:author])
      @showtime = true
      @search_type = "by author"
    end
  end
  
  def confirm_book
  end
  
  def confirm_author_books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventory/_authorbooks.html.erb
<% if @author_entry == true %>
    <div class="mtop-50 row" id="books_by_author">
        <div class="col-md-6 col-md-offset-3 center-it">
            <%= form_tag('/enter_book') do %>
                <p><%= text_field_tag :author, @author_name %></p>
                <p><%= text_field_tag :title, nil, placeholder: "Next Book Title", autofocus: true %></p>
                <p><%= text_field_tag :color, nil, placeholder: "Color of book" %></p>
                <p><%= select_tag :shelf_id, options_from_collection_for_select(@shelves, "id", "designation"), prompt: "Choose a Shelf"%></p>
                <p class="invisible"><%= text_field_tag :author_entry, "true" %></p>
                <div><p><%= submit_tag "Enter Next Title", class: "btn btn-warning" %></p></div>
            <% end %>
        </div>
    </div>
<% else %>
    <div class="invisible mtop-50 row" id="books_by_author">
        <div class="col-md-6 col-md-offset-3 center-it">
            <%= form_tag('/enter_book') do %>
                <p><%= text_field_tag :author, nil, placeholder: "Author", autofocus: true %></p>
                <p><%= text_field_tag :title, nil, placeholder: "First Book Title" %></p>
                <p><%= text_field_tag :color, nil, placeholder: "Color of book" %></p>
                <p><%= select_tag :shelf_id, options_from_collection_for_select(@shelves, "id", "designation"), prompt: "Choose a Shelf"%></p>
                <p class="invisible"><%= text_field_tag :author_entry, "true" %></p>
                <div><p><%= submit_tag "Start Entering Titles", class: "btn btn-warning" %></p></div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/inventory/_onebook.html.erb
<%= form_tag('/enter_book') do %>
    <p><%= text_field_tag :title, nil, placeholder: "Title", autofocus: true %></p>
    <p><%= text_field_tag :author, nil, placeholder: "Author" %></p>
    <p><%= text_field_tag :color, nil, placeholder: "Color of book" %></p>
    <p><%= select_tag :shelf_id, options_from_collection_for_select(@shelves, "id", "designation"), prompt: "Choose a Shelf"%></p>
    <div><p><%= submit_tag "Shelve It!", class: "btn btn-success" %></p></div>
<% end %>

app/views/inventory/enter_book.html.erb
<div class="inventory-pages">
    <div class="enter-books">
        <div class="center-it"><h1>Add to the Stacks!</h1></div>
        <div class="row mtop-50 center-it">
            <div class="col-md-4">
                <button class="btn btn-success" id="just_one">Add One Book</button>
            </div>
            <div class="col-md-8">
                <button class="btn btn-warning" id="many_books">Add Multiple Books by Author</button>
            </div>
        </div>
        <div class="invisible mtop-50 row" id="one_book">
            <div class="col-md-6 col-md-offset-3 center-it">
                <%= render 'onebook' %>
            </div>
        </div>
        
        <%= render 'authorbooks.html.erb' %>
    </div>

    <div class="show-books mtop-50">
        <div class="center-it">
            <span class="pointy" id="show_books">Show Books?</span>
        </div>
        <div class="center-it">
            <span class="invisible pointy" id="hide_books">Hide Books?</span>
        </div>
        <div class="invisible" id="book_table">
            <table class="table">
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Color</th>
                    <th>Shelf</th>
                </tr>
                <% @books.each do |book| %>
                    <tr>
                        <td><%= book.title %></td>
                        <td><%= book.author %></td>
                        <td><%= book.color %></td>
                        <td><%= book.shelf.designation %></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
     $('#just_one').click(function(){
        $('#one_book').toggleClass('invisible');
        $('#books_by_author').addClass('invisible');
     });
     $('#many_books').click(function(){
        $('#books_by_author').toggleClass('invisible');
        $('#one_book').addClass('invisible');
     });
     $('#show_books').click(function(){
        $('#book_table').removeClass('invisible');
        $('#hide_books').removeClass('invisible');
        $(this).addClass('invisible');
     });
     $('#hide_books').click(function(){
        $('#book_table').addClass('invisible');
        $('#show_books').removeClass('invisible');
        $(this).addClass('invisible');
     });
    });
</script>

app/views/inventory/find_book.html.erb
<div class="inventory-pages">
    <div class="find-books center-it">
        <h2>Search by...</h2>
        <div class="mtop-50">
            <%= form_tag('find_book') do %>
                <%= text_field_tag :title, nil, placeholder: "Book Title" %> <%= submit_tag "Check Shelves", class: "btn btn-info" %>
            <% end %>
        </div>
        <div class="mtop-50">
            <%= form_tag('find_book') do %>
                <%= text_field_tag :author, nil, placeholder: "Author" %> <%= submit_tag "Check Shelves", class: "btn btn-success" %>
            <% end %>
        </div>
    </div>
    <% if @showtime == true %>
        <div class="show-books mtop-50 center-it">
            <% if @search_type == "by author" %>
                <table class="table">
                    <tr>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Color</th>
                        <th>Shelf</th>
                    </tr>
                    <% @books.each do |book| %>
                        <tr>
                            <td><strong><%= book.title %></strong></td>
                            <td><%= book.author %></td>
                            <td><%= book.color %></td>
                            <td><strong><%= book.shelf.designation %></strong></td>
                        </tr>
                    <% end %>
                </table>
            <% else %>
                <div>
                    <h5>You're looking for...</h5>
                    <h3><%= @book.title %></h3>
                    <p>by <%= @book.author %></p>
                    <p>It's located on <strong>Shelf <%= @book.shelf.designation %></strong></p>
                </div>
            <% end %>
            <p><%= link_to "Find Another", find_book_path, class: "btn btn-danger" %></p>
        </div>
    <% end %>
</div>

app/views/inventory/index.html.erb
<div class="inventory-pages">
    <div class="enter-or-find">
        <div class="center-it"><h1>What Do You Want to Do Today?</h1></div>
        <div class="row mtop-50">
            <div class="col-md-6 center-it"><%= link_to "Add a Book", enter_book_path, class: "btn btn-success" %></div>
            <div class="col-md-6 center-it"><%= link_to "Find a Book", find_book_path, class: "btn btn-primary" %></div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>Find That Book!</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Find It", find_book_path %></li>
        <li><%= link_to "Enter It", enter_book_path %></li>
      </ul>
    </div>
  </div>
</nav>



<div class="container">
  <%= yield %>
</div>

</body>
</html>